services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: prod
    env_file:
      - .env
    command:
      - uv
      - run
      - --no-dev
      - --frozen
      - nba_ai
    restart: always
    pull_policy: always

volumes: {}
